### ISSUE TITLE
[JENKINS-72658] c:select with readonlyMode still shows an add button and dropdown works or is empty

### ISSUE THREAD

**Issue by jenkins-infra-bot** [jenkinsci/credentials-plugin#952]
<p>When using <c:select> in a jelly file and readonlyMode is enabled, the dropdown is not disables and the add button still works.</p>

<p>I noticed this while working on configfile provider plugin</p>

<p><b>How to reproduce</b></p>
<ol>
	<li>Install these credentials:<br/>
credentials-binding<br/>
extended-read-permission<br/>
matrix.auth</li>
	<li>configure a read only user that has extended read on job</li>
	<li>create a user pwd credential</li>
	<li>create freestyle job and add a credential binding for the user/pwd</li>
	<li>View the job config with the read only user</li>
</ol>

<p><b>Expected</b></p>

<p>The dropdown is disabled and only shows the active value.<br/>
The add button is disabled or not shown at all</p>

<p><b>Actual</b></p>

<p>The dropdown is empty and the button is active but nothing happens when clicking on it.</p>

<p> </p>

<p>In another scenario with configfile provider, there is the ability to view a configfile from a job config. Here the user has job config permissions. On a change that I'm currently working on I use the readonlyMode setting that should disable all inputs but the credentials selection is not disabled.</p>

<p>So when a user has no permissions to create credentials the add button shouldn't be shown at all I think</p>

<p> </p>

<p> </p>

<p> </p>

---
<details><summary><i>Originally reported by <a href="https://issues.jenkins.io/secure/ViewProfile.jspa?name=mawinter69">mawinter69</a>, imported from: <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-72658" target="_blank">c:select with readonlyMode still shows an add button and dropdown works or is empty</a></i></summary>
<i><ul>
<li><b>status</b>: Open
<li><b>priority</b>: Minor
<li><b>component(s)</b>: credentials-plugin
<li><b>resolution</b>: Unresolved
<li><b>votes</b>: 0
<li><b>watchers</b>: 2
<li><b>imported</b>: 2025-12-08
</ul></i>
<details><summary>Raw content of original issue</summary>

<pre>
<p>When using &lt;c:select&gt; in a jelly file and readonlyMode is enabled, the dropdown is not disables and the add button still works.</p>

<p>I noticed this while working on configfile provider plugin</p>

<p><b>How to reproduce</b></p>
<ol>
	<li>Install these credentials:
credentials-binding
extended-read-permission
matrix.auth</li>
	<li>configure a read only user that has extended read on job</li>
	<li>create a user pwd credential</li>
	<li>create freestyle job and add a credential binding for the user/pwd</li>
	<li>View the job config with the read only user</li>
</ol>

<p><b>Expected</b></p>

<p>The dropdown is disabled and only shows the active value.
The add button is disabled or not shown at all</p>

<p><b>Actual</b></p>

<p>The dropdown is empty and the button is active but nothing happens when clicking on it.</p>

<p> </p>

<p>In another scenario with configfile provider, there is the ability to view a configfile from a job config. Here the user has job config permissions. On a change that I'm currently working on I use the readonlyMode setting that should disable all inputs but the credentials selection is not disabled.</p>

<p>So when a user has no permissions to create credentials the add button shouldn't be shown at all I think</p>

<p> </p>

<p> </p>

<p> </p></pre>
</details>
</details>
<ul><li><i>environment</i>: <code>Credentials plugin: 1319.v7eb_51b_3a_c97b_</code></li></ul>
<details><summary><i>2 attachments</i></summary>

- [image-2024-02-14-10-43-51-908.png](https://issues.jenkins.io/secure/attachment/62090/image-2024-02-14-10-43-51-908.png)
  > ![image-2024-02-14-10-43-51-908.png](https://issues.jenkins.io/secure/attachment/62090/image-2024-02-14-10-43-51-908.png)
- [image-2024-02-14-10-46-32-582.png](https://issues.jenkins.io/secure/attachment/62091/image-2024-02-14-10-46-32-582.png)
  > ![image-2024-02-14-10-46-32-582.png](https://issues.jenkins.io/secure/attachment/62091/image-2024-02-14-10-46-32-582.png)
</details>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>mawinter69:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-72658?focusedId=444899&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-444899">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>The dropdown problem seems to be more an issue in core.</p>
</pre>
</details>

</ul>
</details>

<p>The dropdown problem seems to be more an issue in core.</p>

**Comment by jenkins-infra-bot** [comment]
<details><summary><i>chup4chups:</i></summary>

<ul>
<li><i>Original <a class="original-jira-link" href="https://issues.jenkins.io/browse/JENKINS-72658?focusedId=445184&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-445184">comment link</a></i>
<li><details><summary><i>Raw content of original comment:</i></summary>

<pre>
<p>Facing similar issue here for all my configurations using credentials after upgrading from 2.414.3 to 2.426.3</p>
<ul>
	<li>docker image: jenkins/jenkins:2.426.3-lts</li>
	<li>Credentials Plugin: Version1224.vc23ca_a_9a_2cb_0</li>
</ul>


<p>The dropdown is not working and Jenkins Credential Provider is displayed directly below the dropdown.</p>

<p><span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62090/62090_image-2024-02-14-10-43-51-908.png" style="border: 0px solid black" /></span></p>

<p>is this related ?</p>

<p>Also, from chrome console I can see the error below showing multiple time</p>
<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">behavior.js:138 TypeError: $ is not a function
    at select.js:183:15
    at Array.forEach (&lt;anonymous&gt;)
    at behavior.js:135:22
    at Array.forEach (&lt;anonymous&gt;)
    at behavior.js:126:21
    at Array.forEach (&lt;anonymous&gt;)
    at <span class="code-object">Object</span>.applySubtree (behavior.js:107:15)
    at select.js:280:19</pre>
</div></div>
<p>which make me think about a jquery issue but after verifying, we do have jQuery plugin enabled: Version1.12.4-1 </p>

<p>Moreover, after rolling back to the previous version, the dropdown is working fine
<span class="image-wrap" style=""><img src="https://issues.jenkins.io/secure/attachment/62091/62091_image-2024-02-14-10-46-32-582.png" style="border: 0px solid black" /></span></p>

<p>Any idea ?</p>
</pre>
</details>

</ul>
</details>

<p>Facing similar issue here for all my configurations using credentials after upgrading from 2.414.3 to 2.426.3</p>
<ul>
	<li>docker image: jenkins/jenkins:2.426.3-lts</li>
	<li>Credentials Plugin: Version1224.vc23ca_a_9a_2cb_0</li>
</ul>


<p>The dropdown is not working and Jenkins Credential Provider is displayed directly below the dropdown.</p>

<p><span class="image-wrap" style=""><img src="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-misc/refs/heads/main/attachments/62090/image-2024-02-14-10-43-51-908.png" style="border: 0px solid black" /></span></p>

<p>is this related ?</p>

<p>Also, from chrome console I can see the error below showing multiple time</p>

<pre>
behavior.js:138 TypeError: $ is not a function
    at select.js:183:15
    at Array.forEach (<anonymous>)
    at behavior.js:135:22
    at Array.forEach (<anonymous>)
    at behavior.js:126:21
    at Array.forEach (<anonymous>)
    at <span class="code-object">Object</span>.applySubtree (behavior.js:107:15)
    at select.js:280:19</pre>
<p>which make me think about a jquery issue but after verifying, we do have jQuery plugin enabled: Version1.12.4-1 </p>

<p>Moreover, after rolling back to the previous version, the dropdown is working fine<br/>
<span class="image-wrap" style=""><img src="https://raw.githubusercontent.com/jenkinsci/attachments-from-jira-issues-last/refs/heads/main/attachments/62091/image-2024-02-14-10-46-32-582.png" style="border: 0px solid black" /></span></p>

<p>Any idea ?</p>
